# Generated by Django 4.0.1 on 2022-02-08 11:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lexique', '0002_remove_blog_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Lexique',
        ),
    ]
