# Generated by Django 4.0.1 on 2022-02-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maneki',
            old_name='score_hiragana',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='maneki',
            name='score_katakana',
        ),
    ]
