# Generated by Django 4.0.1 on 2022-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
