# Generated by Django 4.0.1 on 2022-02-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_score'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.score'),
        ),
    ]
